services:
  api:
    image: ghcr.io/yousuf-hamoda/ode-solver-api:latest
    container_name: matrix-api
    restart: unless-stopped
    ports:
      - "5050:5050"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  web:
    image: ghcr.io/yousuf-hamoda/ode-solver-web:latest
    container_name: matrix-web
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - api
    labels:
      - "com.centurylinklabs.watchtower.enable=true"