services:
  api:
    image: ghcr.io/yousuf-hamoda/ode-solver-api:latest
    container_name: ode-solver-api
    restart: unless-stopped
    ports:
      - "5050:5050"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  web:
    image: ghcr.io/yousuf-hamoda/ode-solver-web:latest
    container_name: ode-solver-web
    restart: unless-stopped
    ports:
      - "8024:8024"
    depends_on:
      - api
    environment:
      - API_URL=http://api:5050
    labels:
      - "com.centurylinklabs.watchtower.enable=true"